app:
  container_name: app
  restart: always
  build: .
  ports:
    - "4000:4000"
  links:
    - postgres
postgres:
  container_name: postgres
  image: postgres
  expose: 
    - "5432"
  volumes: 
    - ./data:/data/db
  ports:
    - "5432:5432"